In [1]:
import pandas as pd 
import numpy as np

In [2]:
train_features = pd.read_csv(r'C:\Users\hp\Documents\Data Science Projects\phase5_capstone\Early-Detection-of-Alzheimer-s-Disease-and-Related-Dementias-Using-Social-Determinants-of-Health\Original data\train_features.csv')
train_labels = pd.read_csv(r'C:\Users\hp\Documents\Data Science Projects\phase5_capstone\Early-Detection-of-Alzheimer-s-Disease-and-Related-Dementias-Using-Social-Determinants-of-Health\Original data\train_labels.csv')

In [3]:
#merging the dataset
df = pd.merge(train_features, train_labels, on='uid', how='left')
df.head()

,uid,age_03,urban_03,married_03,n_mar_03,edu_gru_03,n_living_child_03,migration_03,glob_hlth_03,adl_dress_03,...,rsocact_m_12,rrelgwk_12,a16a_12,a21_12,a22_12,a33b_12,a34_12,j11_12,year,composite_score
0,aace,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,9.Never,0.No,NaN,NaN,NaN,NaN,NaN,Concrete 2,2021,175
1,aanz,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.Almost every day,0.No,NaN,NaN,NaN,NaN,NaN,Concrete 2,2021,206
2,aape,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.4 or more times a week,0.No,NaN,NaN,NaN,NaN,NaN,"Wood, mosaic, or other covering 1",2016,161
3,aape,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.4 or more times a week,0.No,NaN,NaN,NaN,NaN,NaN,"Wood, mosaic, or other covering 1",2021,144
4,aard,1. 50–59,"1. 100,000+",3. Widowed,1.0,3. 7–9 years,1. 1 or 2,0.0,4. Fair,0.0,...,9.Never,1.Yes,NaN,NaN,NaN,NaN,No 2,Concrete 2,2021,104

In [4]:
#extracting categorical columns
categorical_cols = df.select_dtypes(include=['object']).columns
for col in categorical_cols:
    print(f"Unique values in '{col}': {df[col].unique()}")

Unique values in 'uid': ['aace' 'aanz' 'aape' ... 'zzci' 'zzjb' 'zzti']
Unique values in 'age_03': [nan '1. 50–59' '3. 70–79' '2. 60–69' '0. 49 or younger' '4. 80+']
Unique values in 'urban_03': [nan '1. 100,000+' '0. <100,000']
Unique values in 'married_03': [nan '3. Widowed' '1. Married or in civil union' '4. Single'
 '2. Separated or divorced']
Unique values in 'edu_gru_03': [nan '3. 7–9 years' '1. 1–5 years' '0. No education' '2. 6 years'
 '4. 10+ years']
Unique values in 'n_living_child_03': [nan '1. 1 or 2' '3. 5 or 6' '0. No children' '2. 3 or 4' '4. 7+']
Unique values in 'glob_hlth_03': [nan '4. Fair' '5. Poor' '3. Good' '1. Excellent' '2. Very good']
Unique values in 'bmi_03': [nan '3. Overweight' '4. Obese' '1. Underweight' '2. Normal weight'
 '5. Morbidly obese']
Unique values in 'decis_famil_03': [nan '2. Approximately equal weight' '1. Respondent' '3. Spouse']
Unique values in 'employment_03': [nan '3. Dedicated to household chores' '1. Currently Working'
 '2. Currently looking for work'
 '4. Retired, incapacitated, or does not work']
Unique values in 'age_12': ['2. 60–69' '1. 50–59' '4. 80+' '3. 70–79' nan '0. 49 or younger']
Unique values in 'urban_12': ['0. <100,000' '1. 100,000+' nan]
Unique values in 'married_12': ['1. Married or in civil union' '3. Widowed' '2. Separated or divorced'
 nan '4. Single']
Unique values in 'edu_gru_12': ['0. No education' '3. 7–9 years' '1. 1–5 years' '2. 6 years'
 '4. 10+ years' nan]
Unique values in 'n_living_child_12': ['1. 1 or 2' '3. 5 or 6' '0. No children' '2. 3 or 4' '4. 7+' nan]
Unique values in 'glob_hlth_12': ['4. Fair' '3. Good' '2. Very good' '5. Poor' nan '1. Excellent']
Unique values in 'bmi_12': ['3. Overweight' '4. Obese' '2. Normal weight' nan '1. Underweight'
 '5. Morbidly obese']
Unique values in 'decis_famil_12': ['2. Approximately equal weight' '3. Spouse' nan '1. Respondent']
Unique values in 'decis_personal_12': ['1. A lot' '2. A little' nan '3. None']
Unique values in 'employment_12': ['1. Currently Working' '2. Currently looking for work'
 '3. Dedicated to household chores'
 '4. Retired, incapacitated, or does not work' nan]
Unique values in 'satis_ideal_12': ['3. Disagrees' '1. Agrees' '2. Neither agrees nor disagrees' nan]
Unique values in 'satis_excel_12': ['3. Disagrees' '2. Neither agrees nor disagrees' '1. Agrees' nan]
Unique values in 'satis_fine_12': ['1. Agrees' '3. Disagrees' '2. Neither agrees nor disagrees' nan]
Unique values in 'cosas_imp_12': ['1. Agrees' '2. Neither agrees nor disagrees' '3. Disagrees' nan]
Unique values in 'wouldnt_change_12': ['3. Disagrees' '1. Agrees' '2. Neither agrees nor disagrees' nan]
Unique values in 'memory_12': ['2. Very good' '4. Fair' '3. Good' nan '5. Poor' '1. Excellent']
Unique values in 'ragender': ['1.Man' '2.Woman']
Unique values in 'rameduc_m': ['1.None' '2.Some primary' '3.Primary' nan '4.More than primary']
Unique values in 'rafeduc_m': ['1.None' '2.Some primary' '4.More than primary' '3.Primary' nan]
Unique values in 'sgender_03': [nan '2.Woman' '1.Man']
Unique values in 'rjlocc_m_03': [nan '6.Workers in Agriculture, Livestock, Forestry, and Fishing'
 '18.Safety and Security Personnel'
 '15.Traveling Salespeople and Traveling Salespeople of Services'
 '8.Artisans and Workers in Production, Repair, Maintenance'
 '14.Merchants and Sales Representatives' '1.Professionals'
 '17.Domestic Workers'
 '9.Operators of Fixed Machinery and Equipment for Ind. Production'
 '16.Workers in the Service Industry' '19.Other Workers'
 '11.Drivers and Asst Drivers of Mobile Machinery and Transport Vehicles'
 '10.Asst/Laborers etc in Ind. Production, Repair, Maintenance'
 '13.Administrative Support Staff' '4.Workers in Art, Shows, and Sports'
 '5.Officials and Directors Public, Private, and Social Sectors'
 '3.Educators' '2.Technicians'
 '12.Department Heads/Coordinators/Supervisors in Admin and Service Activities']
Unique values in 'rjobend_reason_03': [nan '4.Health reason' '5.Family reason' '1.Retired' '8.Other'
 '3.Laid off']
Unique values in 'rrelgimp_03': [nan '1.very important' '2.somewhat important' '3.not important']
Unique values in 'sgender_12': ['2.Woman' '1.Man' nan]
Unique values in 'rjlocc_m_12': ['6.Workers in Agriculture, Livestock, Forestry, and Fishing'
 '18.Safety and Security Personnel' nan
 '8.Artisans and Workers in Production, Repair, Maintenance'
 '14.Merchants and Sales Representatives' '17.Domestic Workers'
 '9.Operators of Fixed Machinery and Equipment for Ind. Production'
 '15.Traveling Salespeople and Traveling Salespeople of Services'
 '16.Workers in the Service Industry'
 '4.Workers in Art, Shows, and Sports' '3.Educators'
 '12.Department Heads/Coordinators/Supervisors in Admin and Service Activities'
 '10.Asst/Laborers etc in Ind. Production, Repair, Maintenance'
 '1.Professionals' '13.Administrative Support Staff'
 '11.Drivers and Asst Drivers of Mobile Machinery and Transport Vehicles'
 '7.Bosses/Supervisors etc in Artistic, Ind. Production, Repair, Maintenance Activities'
 '2.Technicians'
 '5.Officials and Directors Public, Private, and Social Sectors']
Unique values in 'rjobend_reason_12': [nan '8.Other' '3.Laid off' '4.Health reason' '5.Family reason'
 '1.Retired']
Unique values in 'rrelgimp_12': ['2.somewhat important' '1.very important' '3.not important' nan]
Unique values in 'rrfcntx_m_12': ['9.Never' '6.2 or 3 times a month' '4.Once a week'
 '3.2 or 3 times a week' '8.Almost Never, sporadic' '1.Almost every day'
 '2.4 or more times a week' '7.Once a month' nan
 '5.4 or more times a month']
Unique values in 'rsocact_m_12': ['9.Never' '1.Almost every day' '2.4 or more times a week'
 '3.2 or 3 times a week' '4.Once a week' '7.Once a month'
 '8.Almost Never, sporadic' nan '6.2 or 3 times a month'
 '5.4 or more times a month']
Unique values in 'rrelgwk_12': ['0.No' '1.Yes' nan]
Unique values in 'a22_12': [nan 'Agriculture/ Animal breeding 01' 'Gardening or maintenance 03'
 'Construction/ Manufacturing/ Mining 02' 'Did not work 08'
 'Childcare or domestic work 04' 'Restaurant/ Store/ Hotel 05' 'Other 07']
Unique values in 'a33b_12': [nan 'Neither 3' 'Permanent resident 1' 'Citizen 2']
Unique values in 'a34_12': [nan 'No 2' 'Yes 1']
Unique values in 'j11_12': ['Concrete 2' 'Wood, mosaic, or other covering 1' 'Mud 3' nan]

In [5]:
columns_to_check = ['decis_famil_03', 'decis_famil_12', 'bmi_03', 'bmi_12', 'rjobend_reason_03', 'rjobend_reason_12', 'rjlocc_m_12', 'rjlocc_m_03']

# List unique values for each column
for column in columns_to_check:
    unique_vals = df[column].unique()
    print(f"Unique va_longalues in '{column}':")
    print(unique_vals)
    print()

Unique va_longalues in 'decis_famil_03':
[nan '2. Approximately equal weight' '1. Respondent' '3. Spouse']

Unique va_longalues in 'decis_famil_12':
['2. Approximately equal weight' '3. Spouse' nan '1. Respondent']

Unique va_longalues in 'bmi_03':
[nan '3. Overweight' '4. Obese' '1. Underweight' '2. Normal weight'
 '5. Morbidly obese']

Unique va_longalues in 'bmi_12':
['3. Overweight' '4. Obese' '2. Normal weight' nan '1. Underweight'
 '5. Morbidly obese']

Unique va_longalues in 'rjobend_reason_03':
[nan '4.Health reason' '5.Family reason' '1.Retired' '8.Other'
 '3.Laid off']

Unique va_longalues in 'rjobend_reason_12':
[nan '8.Other' '3.Laid off' '4.Health reason' '5.Family reason'
 '1.Retired']

Unique va_longalues in 'rjlocc_m_12':
['6.Workers in Agriculture, Livestock, Forestry, and Fishing'
 '18.Safety and Security Personnel' nan
 '8.Artisans and Workers in Production, Repair, Maintenance'
 '14.Merchants and Sales Representatives' '17.Domestic Workers'
 '9.Operators of Fixed Machinery and Equipment for Ind. Production'
 '15.Traveling Salespeople and Traveling Salespeople of Services'
 '16.Workers in the Service Industry'
 '4.Workers in Art, Shows, and Sports' '3.Educators'
 '12.Department Heads/Coordinators/Supervisors in Admin and Service Activities'
 '10.Asst/Laborers etc in Ind. Production, Repair, Maintenance'
 '1.Professionals' '13.Administrative Support Staff'
 '11.Drivers and Asst Drivers of Mobile Machinery and Transport Vehicles'
 '7.Bosses/Supervisors etc in Artistic, Ind. Production, Repair, Maintenance Activities'
 '2.Technicians'
 '5.Officials and Directors Public, Private, and Social Sectors']

Unique va_longalues in 'rjlocc_m_03':
[nan '6.Workers in Agriculture, Livestock, Forestry, and Fishing'
 '18.Safety and Security Personnel'
 '15.Traveling Salespeople and Traveling Salespeople of Services'
 '8.Artisans and Workers in Production, Repair, Maintenance'
 '14.Merchants and Sales Representatives' '1.Professionals'
 '17.Domestic Workers'
 '9.Operators of Fixed Machinery and Equipment for Ind. Production'
 '16.Workers in the Service Industry' '19.Other Workers'
 '11.Drivers and Asst Drivers of Mobile Machinery and Transport Vehicles'
 '10.Asst/Laborers etc in Ind. Production, Repair, Maintenance'
 '13.Administrative Support Staff' '4.Workers in Art, Shows, and Sports'
 '5.Officials and Directors Public, Private, and Social Sectors'
 '3.Educators' '2.Technicians'
 '12.Department Heads/Coordinators/Supervisors in Admin and Service Activities']

In [6]:
# Define mappings for each categorical column
mappings = {
    'age_03': {
        '1. 50–59': 1,
        '3. 70–79': 3,
        '2. 60–69': 2,
        '0. 49 or younger': 0,
        '4. 80+': 4
    },
    'urban_03': {
        '1. 100,000+': 1,
        '0. <100,000': 0
    },
    'married_03': {
        '3. Widowed': 3,
        '1. Married or in civil union': 1,
        '4. Single': 4,
        '2. Separated or divorced': 2
    },
    'edu_gru_03': {
        '3. 7–9 years': 3,
        '1. 1–5 years': 1,
        '0. No education': 0,
        '2. 6 years': 2,
        '4. 10+ years': 4
    },
    'n_living_child_03': {
        '1. 1 or 2': 1,
        '3. 5 or 6': 3,
        '0. No children': 0,
        '2. 3 or 4': 2,
        '4. 7+': 4
    },
    'glob_hlth_03': {
        '4. Fair': 4,
        '5. Poor': 5,
        '3. Good': 3,
        '1. Excellent': 1,
        '2. Very good': 2
    },
    'employment_03': {
        '3. Dedicated to household chores': 3,
        '1. Currently Working': 1,
        '2. Currently looking for work': 2,
        '4. Retired, incapacitated, or does not work': 4
    },
    'age_12': {
        '2. 60–69': 2,
        '1. 50–59': 1,
        '4. 80+': 4,
        '3. 70–79': 3,
        '0. 49 or younger': 0
    },
    'urban_12': {
        '0. <100,000': 0,
        '1. 100,000+': 1
    },
    'married_12': {
        '1. Married or in civil union': 1,
        '3. Widowed': 3,
        '2. Separated or divorced': 2,
        '4. Single': 4
    },
    'edu_gru_12': {
        '0. No education': 0,
        '3. 7–9 years': 3,
        '1. 1–5 years': 1,
        '2. 6 years': 2,
        '4. 10+ years': 4
    },
    'n_living_child_12': {
        '1. 1 or 2': 1,
        '3. 5 or 6': 3,
        '0. No children': 0,
        '2. 3 or 4': 2,
        '4. 7+': 4
    },
    'glob_hlth_12': {
        '4. Fair': 4,
        '3. Good': 3,
        '2. Very good': 2,
        '5. Poor': 5,
        '1. Excellent': 1
    },
    'bmi_12': {
        '3. Overweight': 3,
        '4. Obese': 4,
        '2. Normal weight': 2,
        '1. Underweight': 1,
        '5. Morbidly obese': 5
    },
    'decis_famil_12': {
        '2. Approximately equal weight': 2,
        '3. Spouse': 3,
        '1. Respondent': 1
    },
    'decis_personal_12': {
        '1. A lot': 1,
        '2. A little': 2,
        '3. None': 3
    },
    'employment_12': {
        '1. Currently Working': 1,
        '2. Currently looking for work': 2,
        '3. Dedicated to household chores': 3,
        '4. Retired, incapacitated, or does not work': 4
    },
    'satis_ideal_12': {
        '3. Disagrees': 3,
        '1. Agrees': 1,
        '2. Neither agrees nor disagrees': 2
    },
    'satis_excel_12': {
        '3. Disagrees': 3,
        '2. Neither agrees nor disagrees': 2,
        '1. Agrees': 1
    },
    'satis_fine_12': {
        '1. Agrees': 1,
        '3. Disagrees': 3,
        '2. Neither agrees nor disagrees': 2
    },
    'cosas_imp_12': {
        '1. Agrees': 1,
        '2. Neither agrees nor disagrees': 2,
        '3. Disagrees': 3
    },
    'wouldnt_change_12': {
        '3. Disagrees': 3,
        '1. Agrees': 1,
        '2. Neither agrees nor disagrees': 2
    },
    'memory_12': {
        '2. Very good': 2,
        '4. Fair': 4,
        '3. Good': 3,
        '5. Poor': 5,
        '1. Excellent': 1
    },
    'ragender': {
        '1.Man': 1,
        '2.Woman': 2
    },
    'rameduc_m': {
        '1.None': 1,
        '2.Some primary': 2,
        '3.Primary': 3,
        '4.More than primary': 4
    },
    'rafeduc_m': {
        '1.None': 1,
        '2.Some primary': 2,
        '4.More than primary': 4,
        '3.Primary': 3
    },
    'sgender_03': {
        '2.Woman': 2,
        '1.Man': 1
    },
    'rrelgimp_03': {
        '1.very important': 1,
        '2.somewhat important': 2,
        '3.not important': 3
    },
    'sgender_12': {
        '2.Woman': 2,
        '1.Man': 1
    },
    'rjlocc_m_12': {
        '6.Workers in Agriculture, Livestock, Forestry, and Fishing': 6,
        '18.Safety and Security Personnel': 18,
        '8.Artisans and Workers in Production, Repair, Maintenance': 8,
        '14.Merchants and Sales Representatives': 14,
        '17.Domestic Workers': 17,
        '9.Operators of Fixed Machinery and Equipment for Ind. Production': 9,
        '15.Traveling Salespeople and Traveling Salespeople of Services': 15,
        '16.Workers in the Service Industry': 16,
        '4.Workers in Art, Shows, and Sports': 4,
        '3.Educators': 3,
        '12.Department Heads/Coordinators/Supervisors in Admin and Service Activities': 12,
        '10.Asst/Laborers etc in Ind. Production, Repair, Maintenance': 10,
        '1.Professionals': 1,
        '13.Administrative Support Staff': 13,
        '11.Drivers and Asst Drivers of Mobile Machinery and Transport Vehicles': 11,
        '7.Bosses/Supervisors etc in Artistic, Ind. Production, Repair, Maintenance Activities': 7,
        '2.Technicians': 2,
        '5.Officials and Directors Public, Private, and Social Sectors': 5
    },
    'rrelgimp_12': {
        '2.somewhat important': 2,
        '1.very important': 1,
        '3.not important': 3
    },
    'rrfcntx_m_12': {
        '9.Never': 9,
        '6.2 or 3 times a month': 6,
        '4.Once a week': 4,
        '3.2 or 3 times a week': 3,
        '8.Almost Never, sporadic': 8,
        '1.Almost every day': 1,
        '2.4 or more times a week': 2,
        '7.Once a month': 7,
        '5.4 or more times a month': 5
    },
    'rsocact_m_12': {
        '9.Never': 9,
        '1.Almost every day': 1,
        '2.4 or more times a week': 2,
        '3.2 or 3 times a week': 3,
        '4.Once a week': 4,
        '8.Almost Never, sporadic': 8,
        '5.2 or 3 times a month': 5,
        '6.Once a month': 6,
        '7.4 or more times a month': 7
    },
    'rrelgwk_12': {
        '0.No': 0,
        '1.Yes': 1
    },
    'a34_12': {
        'No 2': 0,
        'Yes 1': 1
    },
    'j11_12': {
        'Wood, mosaic, or other covering 1': 1,
        'Concrete 2': 2,
        'Mud 3': 3
    }
    }

In [7]:
#applying the mappings to the columns 
for column, mapping in mappings.items():
    df[column] = df[column].map(mapping)

df.head()

,uid,age_03,urban_03,married_03,n_mar_03,edu_gru_03,n_living_child_03,migration_03,glob_hlth_03,adl_dress_03,...,rsocact_m_12,rrelgwk_12,a16a_12,a21_12,a22_12,a33b_12,a34_12,j11_12,year,composite_score
0,aace,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,9.0,0.0,NaN,NaN,NaN,NaN,NaN,2.0,2021,175
1,aanz,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.0,0.0,NaN,NaN,NaN,NaN,NaN,2.0,2021,206
2,aape,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.0,0.0,NaN,NaN,NaN,NaN,NaN,1.0,2016,161
3,aape,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.0,0.0,NaN,NaN,NaN,NaN,NaN,1.0,2021,144
4,aard,1.0,1.0,3.0,1.0,3.0,1.0,0.0,4.0,0.0,...,9.0,1.0,NaN,NaN,NaN,NaN,0.0,2.0,2021,104

**DATA PREPROCESSING**

In [8]:
#converting data from long format to wide format
df.columns.to_list()

['uid',
 'age_03',
 'urban_03',
 'married_03',
 'n_mar_03',
 'edu_gru_03',
 'n_living_child_03',
 'migration_03',
 'glob_hlth_03',
 'adl_dress_03',
 'adl_walk_03',
 'adl_bath_03',
 'adl_eat_03',
 'adl_bed_03',
 'adl_toilet_03',
 'n_adl_03',
 'iadl_money_03',
 'iadl_meds_03',
 'iadl_shop_03',
 'iadl_meals_03',
 'n_iadl_03',
 'depressed_03',
 'hard_03',
 'restless_03',
 'happy_03',
 'lonely_03',
 'enjoy_03',
 'sad_03',
 'tired_03',
 'energetic_03',
 'n_depr_03',
 'cesd_depressed_03',
 'hypertension_03',
 'diabetes_03',
 'resp_ill_03',
 'arthritis_03',
 'hrt_attack_03',
 'stroke_03',
 'cancer_03',
 'n_illnesses_03',
 'bmi_03',
 'exer_3xwk_03',
 'alcohol_03',
 'tobacco_03',
 'test_chol_03',
 'test_tuber_03',
 'test_diab_03',
 'test_pres_03',
 'hosp_03',
 'visit_med_03',
 'out_proc_03',
 'visit_dental_03',
 'imss_03',
 'issste_03',
 'pem_def_mar_03',
 'insur_private_03',
 'insur_other_03',
 'insured_03',
 'decis_famil_03',
 'decis_personal_03',
 'employment_03',
 'age_12',
 'urban_12',
 'married_12',
 'n_mar_12',
 'edu_gru_12',
 'n_living_child_12',
 'migration_12',
 'glob_hlth_12',
 'adl_dress_12',
 'adl_walk_12',
 'adl_bath_12',
 'adl_eat_12',
 'adl_bed_12',
 'adl_toilet_12',
 'n_adl_12',
 'iadl_money_12',
 'iadl_meds_12',
 'iadl_shop_12',
 'iadl_meals_12',
 'n_iadl_12',
 'depressed_12',
 'hard_12',
 'restless_12',
 'happy_12',
 'lonely_12',
 'enjoy_12',
 'sad_12',
 'tired_12',
 'energetic_12',
 'n_depr_12',
 'cesd_depressed_12',
 'hypertension_12',
 'diabetes_12',
 'resp_ill_12',
 'arthritis_12',
 'hrt_attack_12',
 'stroke_12',
 'cancer_12',
 'n_illnesses_12',
 'bmi_12',
 'exer_3xwk_12',
 'alcohol_12',
 'tobacco_12',
 'test_chol_12',
 'test_tuber_12',
 'test_diab_12',
 'test_pres_12',
 'hosp_12',
 'visit_med_12',
 'out_proc_12',
 'visit_dental_12',
 'imss_12',
 'issste_12',
 'pem_def_mar_12',
 'insur_private_12',
 'insur_other_12',
 'insured_12',
 'decis_famil_12',
 'decis_personal_12',
 'employment_12',
 'vax_flu_12',
 'vax_pneu_12',
 'seg_pop_12',
 'care_adult_12',
 'care_child_12',
 'volunteer_12',
 'attends_class_12',
 'attends_club_12',
 'reads_12',
 'games_12',
 'table_games_12',
 'comms_tel_comp_12',
 'act_mant_12',
 'tv_12',
 'sewing_12',
 'satis_ideal_12',
 'satis_excel_12',
 'satis_fine_12',
 'cosas_imp_12',
 'wouldnt_change_12',
 'memory_12',
 'ragender',
 'rameduc_m',
 'rafeduc_m',
 'sgender_03',
 'rjob_hrswk_03',
 'rjlocc_m_03',
 'rjob_end_03',
 'rjobend_reason_03',
 'rearnings_03',
 'searnings_03',
 'hincome_03',
 'hinc_business_03',
 'hinc_rent_03',
 'hinc_assets_03',
 'hinc_cap_03',
 'rinc_pension_03',
 'sinc_pension_03',
 'rrelgimp_03',
 'sgender_12',
 'rjob_hrswk_12',
 'rjlocc_m_12',
 'rjob_end_12',
 'rjobend_reason_12',
 'rearnings_12',
 'searnings_12',
 'hincome_12',
 'hinc_business_12',
 'hinc_rent_12',
 'hinc_assets_12',
 'hinc_cap_12',
 'rinc_pension_12',
 'sinc_pension_12',
 'rrelgimp_12',
 'rrfcntx_m_12',
 'rsocact_m_12',
 'rrelgwk_12',
 'a16a_12',
 'a21_12',
 'a22_12',
 'a33b_12',
 'a34_12',
 'j11_12',
 'year',
 'composite_score']

In [9]:
print("Duplicate 'uid' entries: ", df['uid'].duplicated().sum())

Duplicate 'uid' entries:  1067

In [10]:
stubnames = [col.rsplit('_', 1)[0] for col in df.columns if col.endswith('_03') or col.endswith('_12')]
stubnames = list(set(stubnames))

id_vars = ['uid', 'ragender', 'rameduc_m', 'rafeduc_m', 'year', 'composite_score']

# Reshape the DataFrame using pd.wide_to_long
data_long = pd.wide_to_long(
    df,
    stubnames=stubnames,
    i=['uid', 'year', 'composite_score'],  # Keep 'uid', 'year', and 'composite_score' as identifiers
    j='time',                             # 'time' captures whether it's '03' or '12'
    sep='_',                               # Separator between variable names and time points
    suffix='\\d+'                          # Suffix regex to match '03' and '12'
).reset_index()

In [11]:
data_long.head()

,uid,year,composite_score,time,rafeduc_m,rameduc_m,ragender,iadl_meals,test_chol,a16a,...,hinc_cap,comms_tel_comp,adl_bath,games,act_mant,rearnings,hosp,glob_hlth,n_depr,tobacco
0,aace,2021,175,3,1.0,1.0,1,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,aace,2021,175,12,1.0,1.0,1,0.0,0.0,NaN,...,10000.0,0.0,NaN,0.0,1.0,0.0,0.0,4.0,0.0,0.0
2,aanz,2021,206,3,1.0,1.0,1,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,aanz,2021,206,12,1.0,1.0,1,0.0,1.0,NaN,...,0.0,0.0,0.0,1.0,1.0,70000.0,0.0,4.0,4.0,0.0
4,aape,2016,161,3,2.0,2.0,2,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
# Calculate the percentage of missing values in each column
missing_percentage = data_long.isnull().mean() * 100

# Display the columns with missing values and their percentages
missing_percentage = missing_percentage[missing_percentage > 0].sort_values(ascending=False)
missing_percentage

a16a             99.608566
a22              99.447387
a21              99.366797
a33b             99.366797
rjob_end         87.381994
                   ...
hinc_cap         17.798757
hinc_rent        17.798757
hinc_business    17.798757
rafeduc_m        14.736357
rameduc_m        12.318674
Length: 107, dtype: float64

In [13]:
categorical_columns = data_long.select_dtypes(include=['object', 'category'])
categorical_columns.columns

Index(['uid', 'decis_famil', 'rjlocc_m', 'a33b', 'rjobend_reason', 'bmi',
       'a22'],
      dtype='object')

In [14]:
columns_to_drop = missing_percentage[missing_percentage > 50].index

# Drop the columns
data_long = data_long.drop(columns=columns_to_drop)
data_long.shape

(8686, 78)

In [16]:
data_long.head()

,uid,year,composite_score,time,rafeduc_m,rameduc_m,ragender,iadl_meals,test_chol,insur_private,...,adl_toilet,adl_dress,hinc_assets,hinc_cap,adl_bath,rearnings,hosp,glob_hlth,n_depr,tobacco
0,aace,2021,175,3,1.0,1.0,1,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,aace,2021,175,12,1.0,1.0,1,0.0,0.0,0.0,...,NaN,0.0,0.0,10000.0,NaN,0.0,0.0,4.0,0.0,0.0
2,aanz,2021,206,3,1.0,1.0,1,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,aanz,2021,206,12,1.0,1.0,1,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,70000.0,0.0,4.0,4.0,0.0
4,aape,2016,161,3,2.0,2.0,2,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [24]:
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.linear_model import Ridge
from sklearn.metrics import mean_squared_error, make_scorer, fbeta_score
from sklearn.base import BaseEstimator, TransformerMixin

In [25]:
class ConvertToString(BaseEstimator, TransformerMixin):
    def fit(self, X, y=None):
        return self
    
    def transform(self, X, y=None):
        return X.astype(str)

In [26]:
X = data_long.drop(['composite_score','year'], axis=1)
y = data_long['composite_score']

# Separate numerical and categorical columns
num_cols = X.select_dtypes(include=['float64', 'int64']).columns.tolist()
cat_cols = X.select_dtypes(include=['object']).columns.tolist()

# Define preprocessing for numerical data (imputation + scaling)
num_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='mean')),
    ('scaler', StandardScaler())
])

# Define preprocessing for categorical data (imputation + one-hot encoding)
cat_transformer = Pipeline(steps=[
    ('to_string', ConvertToString()),  # Ensure all categorical data is string type
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('onehot', OneHotEncoder(handle_unknown='ignore'))
])

# Combine preprocessing steps for numerical and categorical columns
preprocessor = ColumnTransformer(
    transformers=[
        ('num', num_transformer, num_cols),
        ('cat', cat_transformer, cat_cols)
    ]
)

In [27]:
# Create pipeline with preprocessing and Ridge regression model
pipeline = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('model', Ridge())
])

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [28]:
X_train.head()

,uid,time,rafeduc_m,rameduc_m,ragender,iadl_meals,test_chol,insur_private,decis_famil,test_pres,...,adl_toilet,adl_dress,hinc_assets,hinc_cap,adl_bath,rearnings,hosp,glob_hlth,n_depr,tobacco
8169,yoxr,12,2.0,1.0,2,0.0,1.0,0.0,NaN,1.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,4.0,6.0,0.0
500,boue,3,2.0,1.0,2,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7197,vtmx,12,1.0,1.0,2,0.0,1.0,0.0,NaN,1.0,...,0.0,0.0,0.0,20000.0,0.0,0.0,0.0,3.0,5.0,0.0
437,bkzc,12,1.0,1.0,2,0.0,1.0,0.0,2.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,6.0,0.0
3912,lztv,3,1.0,1.0,2,0.0,1.0,0.0,3. Spouse,1.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,4.0,6.0,0.0

In [29]:
pipeline.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer()),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['time', 'rafeduc_m',
                                                   'rameduc_m', 'ragender',
                                                   'iadl_meals', 'test_chol',
                                                   'insur_private', 'test_pres',
                                                   'rinc_pension', 'iadl_money',
                                                   'searnings', 'hinc_business',
                                                   'adl_eat', 'n_illnesses',
                                                   'resp_ill', 'n_mar',
                                                   'energetic...hrt_attack',
                                                   'imss', 'stroke',
                                                   'n_living_child',
                                                   'insur_other', 'married',
                                                   'hypertension', 'hard',
                                                   'restless', 'n_adl',
                                                   'insured', 'enjoy', 'sad', ...]),
                                                 ('cat',
                                                  Pipeline(steps=[('to_string',
                                                                   ConvertToString()),
                                                                  ('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('onehot',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['uid', 'decis_famil',
                                                   'bmi'])])),
                ('model', Ridge())])

In [30]:
# Fit the pipeline on the training data
pipeline.fit(X_train, y_train)

# Make predictions and evaluate the model
y_pred = pipeline.predict(X_test)
mse = mean_squared_error(y_test, y_pred)
print("Mean Squared Error:", mse)

Mean Squared Error: 847.361755757437

#### EVALUATION

In [31]:
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import numpy as np

# Calculate evaluation metrics
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
mae = mean_absolute_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

# Print the metrics
print(f"Mean Squared Error (MSE): {mse}")
print(f"Root Mean Squared Error (RMSE): {rmse}")
print(f"Mean Absolute Error (MAE): {mae}")
print(f"R-squared (R²): {r2}")

Mean Squared Error (MSE): 847.361755757437
Root Mean Squared Error (RMSE): 29.109478795702216
Mean Absolute Error (MAE): 22.438892032277753
R-squared (R²): 0.7684717979770948

In [33]:
from sklearn.linear_model import Ridge
from sklearn.model_selection import GridSearchCV

pipeline = Pipeline([
    ('preprocessor', preprocessor),
    ('ridge', Ridge())
])

# Hyperparameter tuning with GridSearchCV
param_grid = {
    'ridge__alpha': [0.01, 0.1, 1, 10, 100],
    'ridge__solver': ['auto', 'svd', 'cholesky', 'lsqr', 'sparse_cg', 'sag', 'saga']
}

grid_search = GridSearchCV(pipeline, param_grid, cv=5, scoring='neg_mean_squared_error')
grid_search.fit(X_train, y_train)

# Best model evaluation
best_model = grid_search.best_estimator_
y_pred = best_model.predict(X_test)

# Calculate evaluation metrics
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
mae = mean_absolute_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("Optimized Ridge Regression Pipeline Performance:")
print(f"Mean Squared Error (MSE): {mse}")
print(f"Root Mean Squared Error (RMSE): {rmse}")
print(f"Mean Absolute Error (MAE): {mae}")
print(f"R-squared (R²): {r2}")

c:\Users\hp\anaconda\envs\learn-env\lib\site-packages\sklearn\model_selection\_validation.py:425: FitFailedWarning:
75 fits failed out of a total of 175.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
25 fits failed with the following error:
Traceback (most recent call last):
  File "c:\Users\hp\anaconda\envs\learn-env\lib\site-packages\sklearn\model_selection\_validation.py", line 729, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "c:\Users\hp\anaconda\envs\learn-env\lib\site-packages\sklearn\base.py", line 1152, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "c:\Users\hp\anaconda\envs\learn-env\lib\site-packages\sklearn\pipeline.py", line 427, in fit
    self._final_estimator.fit(Xt, y, **fit_params_last_step)
  File "c:\Users\hp\anaconda\envs\learn-env\lib\site-packages\sklearn\base.py", line 1152, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "c:\Users\hp\anaconda\envs\learn-env\lib\site-packages\sklearn\linear_model\_ridge.py", line 1131, in fit
    return super().fit(X, y, sample_weight=sample_weight)
  File "c:\Users\hp\anaconda\envs\learn-env\lib\site-packages\sklearn\linear_model\_ridge.py", line 823, in fit
    raise ValueError(
ValueError: solver='svd' does not support fitting the intercept on sparse data. Please set the solver to 'auto' or 'lsqr', 'sparse_cg', 'sag', 'lbfgs' or set `fit_intercept=False`

--------------------------------------------------------------------------------
25 fits failed with the following error:
Traceback (most recent call last):
  File "c:\Users\hp\anaconda\envs\learn-env\lib\site-packages\sklearn\model_selection\_validation.py", line 729, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "c:\Users\hp\anaconda\envs\learn-env\lib\site-packages\sklearn\base.py", line 1152, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "c:\Users\hp\anaconda\envs\learn-env\lib\site-packages\sklearn\pipeline.py", line 427, in fit
    self._final_estimator.fit(Xt, y, **fit_params_last_step)
  File "c:\Users\hp\anaconda\envs\learn-env\lib\site-packages\sklearn\base.py", line 1152, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "c:\Users\hp\anaconda\envs\learn-env\lib\site-packages\sklearn\linear_model\_ridge.py", line 1131, in fit
    return super().fit(X, y, sample_weight=sample_weight)
  File "c:\Users\hp\anaconda\envs\learn-env\lib\site-packages\sklearn\linear_model\_ridge.py", line 823, in fit
    raise ValueError(
ValueError: solver='cholesky' does not support fitting the intercept on sparse data. Please set the solver to 'auto' or 'lsqr', 'sparse_cg', 'sag', 'lbfgs' or set `fit_intercept=False`

--------------------------------------------------------------------------------
25 fits failed with the following error:
Traceback (most recent call last):
  File "c:\Users\hp\anaconda\envs\learn-env\lib\site-packages\sklearn\model_selection\_validation.py", line 729, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "c:\Users\hp\anaconda\envs\learn-env\lib\site-packages\sklearn\base.py", line 1152, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "c:\Users\hp\anaconda\envs\learn-env\lib\site-packages\sklearn\pipeline.py", line 427, in fit
    self._final_estimator.fit(Xt, y, **fit_params_last_step)
  File "c:\Users\hp\anaconda\envs\learn-env\lib\site-packages\sklearn\base.py", line 1152, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "c:\Users\hp\anaconda\envs\learn-env\lib\site-packages\sklearn\linear_model\_ridge.py", line 1131, in fit
    return super().fit(X, y, sample_weight=sample_weight)
  File "c:\Users\hp\anaconda\envs\learn-env\lib\site-packages\sklearn\linear_model\_ridge.py", line 823, in fit
    raise ValueError(
ValueError: solver='saga' does not support fitting the intercept on sparse data. Please set the solver to 'auto' or 'lsqr', 'sparse_cg', 'sag', 'lbfgs' or set `fit_intercept=False`

  warnings.warn(some_fits_failed_message, FitFailedWarning)
c:\Users\hp\anaconda\envs\learn-env\lib\site-packages\sklearn\model_selection\_search.py:979: UserWarning: One or more of the test scores are non-finite: [ -898.30967933            nan            nan  -896.46212834
  -898.30967933  -898.30967933            nan  -837.63046065
            nan            nan  -840.79835516  -837.63046065
  -837.63046065            nan -1109.66728769            nan
            nan -1119.92974435 -1109.66728769 -1109.66728769
            nan -1824.88941384            nan            nan
 -1827.8270504  -1824.88941384 -1824.88941384            nan
 -2088.68529816            nan            nan -2088.61722288
 -2088.68529816 -2088.68529816            nan]
  warnings.warn(

Optimized Ridge Regression Pipeline Performance:
Mean Squared Error (MSE): 504.5516002867027
Root Mean Squared Error (RMSE): 22.46222607594142
Mean Absolute Error (MAE): 15.007964275480507
R-squared (R²): 0.8621392527472059

In [34]:
# Updated Preprocessor with OneHotEncoder producing dense output
preprocessor = ColumnTransformer(
    transformers=[
        ('num', Pipeline([
            ('imputer', SimpleImputer(strategy='mean')),
            ('scaler', StandardScaler())
        ]), num_cols),
        
        ('cat', Pipeline([
            ('imputer', SimpleImputer(strategy='most_frequent')),
            ('encoder', OneHotEncoder(handle_unknown='ignore', sparse_output=False))
        ]), cat_cols)
    ]
)

# Adjusted Pipeline with compatible solvers
param_grid = {
    'ridge__alpha': [0.01, 0.1, 1, 10, 100],
    'ridge__solver': ['auto', 'lsqr', 'sparse_cg', 'sag', 'lbfgs']
}

# Rest of your code
grid_search = GridSearchCV(pipeline, param_grid, cv=5, scoring='neg_mean_squared_error')
grid_search.fit(X_train, y_train)

# Evaluation remains the same
best_model = grid_search.best_estimator_
y_pred = best_model.predict(X_test)

# Calculate evaluation metrics
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
mae = mean_absolute_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("Optimized Ridge Regression Pipeline Performance:")
print(f"Mean Squared Error (MSE): {mse}")
print(f"Root Mean Squared Error (RMSE): {rmse}")
print(f"Mean Absolute Error (MAE): {mae}")
print(f"R-squared (R²): {r2}")

c:\Users\hp\anaconda\envs\learn-env\lib\site-packages\sklearn\model_selection\_validation.py:425: FitFailedWarning:
25 fits failed out of a total of 125.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
25 fits failed with the following error:
Traceback (most recent call last):
  File "c:\Users\hp\anaconda\envs\learn-env\lib\site-packages\sklearn\model_selection\_validation.py", line 729, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "c:\Users\hp\anaconda\envs\learn-env\lib\site-packages\sklearn\base.py", line 1152, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "c:\Users\hp\anaconda\envs\learn-env\lib\site-packages\sklearn\pipeline.py", line 427, in fit
    self._final_estimator.fit(Xt, y, **fit_params_last_step)
  File "c:\Users\hp\anaconda\envs\learn-env\lib\site-packages\sklearn\base.py", line 1152, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "c:\Users\hp\anaconda\envs\learn-env\lib\site-packages\sklearn\linear_model\_ridge.py", line 1131, in fit
    return super().fit(X, y, sample_weight=sample_weight)
  File "c:\Users\hp\anaconda\envs\learn-env\lib\site-packages\sklearn\linear_model\_ridge.py", line 808, in fit
    raise ValueError(
ValueError: 'lbfgs' solver can be used only when positive=True. Please use another solver.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
c:\Users\hp\anaconda\envs\learn-env\lib\site-packages\sklearn\model_selection\_search.py:979: UserWarning: One or more of the test scores are non-finite: [ -898.30967933  -896.46212834  -898.30967933  -898.30967933
            nan  -837.63046065  -840.79835516  -837.63046065
  -837.63046065            nan -1109.66728769 -1119.92974435
 -1109.66728769 -1109.66728769            nan -1824.88941384
 -1827.8270504  -1824.88941384 -1824.88941384            nan
 -2088.68529816 -2088.61722288 -2088.68529816 -2088.68529816
            nan]
  warnings.warn(

Optimized Ridge Regression Pipeline Performance:
Mean Squared Error (MSE): 504.5516002867027
Root Mean Squared Error (RMSE): 22.46222607594142
Mean Absolute Error (MAE): 15.007964275480507
R-squared (R²): 0.8621392527472059